demoapp/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('accounts/',include('django.contrib.auth.urls')),
    path('polls/',include('polls.urls')),
    path('admin/', admin.site.urls),

]

polls/urls.py
from django.urls import path
from . import views
app_name='polls'
urlpatterns=[
    path('',views.index,name='index'),
    path('<int:question_id>/',views.details,name='details'),
    path('<int:question_id>/results/',views.results,name='results'),
    path('<int:question_id>/vote/',views.vote,name='vote'),
]

polls/models.py
from django.db import models
from django.utils import timezone
import datetime
# Create your models here.
class Question(models.Model):
    question_t=models.CharField(max_length=100,unique=True)
    pub_date=models.DateTimeField('date published')

    def __str__(self):
        return self.question_t

    def was_published_recently(self):
        time=timezone.now()
        return self.pub_date <= time

class Choice(models.Model):
    choice_t=models.CharField(max_length=100)
    votes=models.IntegerField(default=0)
    question=models.ForeignKey(Question,on_delete=models.CASCADE)

    def __str__(self):
        return self.choice_t

polls/views.py
from django.shortcuts import render,render_to_response,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from django.template import loader
from .models import *
from django.http import Http404
from django.urls import reverse
from django.utils import timezone
import datetime
from django.core.exceptions import *
# Create your views here.
def index(request):
    ques_list=Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]
#    output='\n'.join([x.question_t for x in ques_list])
    return render(request,'polls/index.html',{'ques_list':ques_list})

def details(request,question_id):
    ques=get_object_or_404(Question,pk=question_id)
    #ques=Question.objects.get(pk=question_id)
    return render(request,'polls/details.html',{'ques':ques})

def results(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    return render(request,'polls/results.html',{'question':question})

def vote(request,question_id):
    question=get_object_or_404(Question,pk=question_id)
    selected_choice=question.choice_set.get(pk=request.POST['choice'])
    selected_choice.votes+=1
    selected_choice.save()
    return HttpResponseRedirect(reverse('polls:results', args=[question.id]))

polls/templates/polls/details.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <meta charset="utf-8">
    <title>Details</title>
  </head>
  <body>
    <hl>{{ques.question_t}}</h1>
    {% if error_message %}
    <p><strong>{{error_message}}</strong></p>
    {% endif %}
    <form action= "{% url 'polls:vote' ques.id %}" method="post">
      {% csrf_token %}
      {% for ch in ques.choice_set.all %}
      <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ch.id}}"/>
      <label for="choice{{forloop.counter}}">{{ch.choice_t}}</label><br/>
      {% endfor %}
      <input type="submit" value="Vote"/>
    </form>
  </body>
</html>

polls/templates/polls/index.html
<!DOCTYPE html>
<html>
<head>
  <title>Latest questions</title>
</head>
<body>
{% load static %}
<link rel="stylesheet" type="text/css" href="{ % static 'polls/style.css' %}"/>
{% if ques_list %}
  <ul>
    {% for question in ques_list %}
      <li><a href="{% url 'polls:details' question.id %}">{{ question.question_t }}</a></li>
    {% endfor %}
  </ul>
{% else %}
  <p>No questions available</p>
{% endif %}
</body>
</html>

polls/templates/polls/results.html
<!DOCTYPE html>
<html lang="en" dir="ltr">
  <head>
    <title>Results page</title>
  </head>
  <body>
    <h1>{{question.question_t}}</h1>
    {%for ch in question.choice_set.all%}
      <li>{{ ch.choice_t }} -- {{ ch.votes }} vote{{ ch.votes|pluralize }}</li>
    {% endfor %}

  </body>
</html>